"""Generic compression spring solver and FreeCAD-backed model export."""

from .api import export_spring_model, solve_and_export, solve_spring
from .models import (
    CandidateFit,
    CandidateGeometry,
    CandidatePhysics,
    CandidateScore,
    ForceBand,
    MassBudgetConfig,
    MassBudgetFixedItemConfig,
    MassBudgetGeometryItemConfig,
    MassBudgetResult,
    ResolvedSpringPayload,
    ScoreWeights,
    SpringCandidate,
    SpringForceTargets,
    SpringGeometryInputs,
    SpringModelExportRequest,
    SpringModelExportResult,
    SpringSearchDiagnosticsPayload,
    SpringSearchGeometry,
    SpringSizingConfig,
    SpringSolveAndExportRequest,
    SpringSolveAndExportResult,
    SpringSolveRequest,
    SpringSolveResult,
    SpringSolverInputs,
    SpringSupportAnnulus,
)
from .tokens import SpringEndType, SpringSolverStatus

__all__ = [
    "CandidateFit",
    "CandidateGeometry",
    "CandidatePhysics",
    "CandidateScore",
    "ForceBand",
    "MassBudgetConfig",
    "MassBudgetFixedItemConfig",
    "MassBudgetGeometryItemConfig",
    "MassBudgetResult",
    "ResolvedSpringPayload",
    "ScoreWeights",
    "SpringCandidate",
    "SpringEndType",
    "SpringForceTargets",
    "SpringGeometryInputs",
    "SpringModelExportRequest",
    "SpringModelExportResult",
    "SpringSearchDiagnosticsPayload",
    "SpringSearchGeometry",
    "SpringSizingConfig",
    "SpringSolveAndExportRequest",
    "SpringSolveAndExportResult",
    "SpringSolveRequest",
    "SpringSolveResult",
    "SpringSolverInputs",
    "SpringSolverStatus",
    "SpringSupportAnnulus",
    "export_spring_model",
    "solve_and_export",
    "solve_spring",
]
